from .nodes import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_2, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_2
from .videoAutomation import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_5, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_5

NODE_CLASS_MAPPINGS = {
    **NODE_CLASS_MAPPINGS_2,
    **NODE_CLASS_MAPPINGS_5,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **NODE_DISPLAY_NAME_MAPPINGS_2,
    **NODE_DISPLAY_NAME_MAPPINGS_5,
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
